### ISSUE TITLE
[FEATURE] - Gebruik heading style class van andere heading

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-titles#52]
**Wat moet er gebeuren**
Op volgende demo pagina, https://overheid.vlaanderen.be/webuniversum/demo/hv.html,
heb ik het onderstaande HTML code gevonden in de sources:

`<h2 class="h3">Officiële gegevens van de hobbyvereniging</h2>`

Hier wordt dus een h3 class op een h2 tag gezet.

In de web component implementatie is dergelijke combinatie niet toegestaan.

Is dit een fout bij het Webuniversum voorbeeld?
Of is dit bewust? Bijvoorbeeld om toch een correcte structuur h1 > h2 > h3 ... te hebben maar de grootte van de tekst te beperken?

In het eerste geval moet Webuniversum hun voorbeeld aanpassen. In het laatste geval moeten dit ook ondersteund worden.

Omwille van WCAG compliancy wil je het niveau van headings respecteren, maar vb niet de té grote tekst hebben. Momenteel hebben wij als work-around, het overridden van de CSS...

**Comment by coemans** [comment]
Zoals eerder gecommuniceerd, zijn de demo pagina's van Webuniversum niet altijd en overal up to date.

@kevcraey, bij voorkeur richt ik me alleen tot Webuniversum wanneer het noodzakelijk is, maar ik laat de keuze over aan jou.

Ik adviseer alvast om geen CSS te overschrijven. Een correcte, WCAG conforme en HTML valid structuur kan steeds bereikt worden door headings over te slaan.

```HTML
<h1 is="vl-h1">Dit is een vl-h1</h1>
<h2 is="vl-h2">Dit is een vl-h2</h2>
<h6 is="vl-h6" alt>Dit is een vl-h6</h6>
```

**Comment by driesva** [comment]
@philipperutten had ons aanbevolen om steeds te starten met _h1_.

Wat betreft over te slaan, op [deze site ](https://www.w3.org/WAI/tutorials/page-structure/headings/) staat nochtans:

> Skipping heading ranks can be confusing and should be avoided where possible: Make sure that a \<h2\> is not followed directly by an \<h4\>, for example.

**Comment by kevcraey** [comment]
Webuniversum heeft al meermaals aangegeven dat hun demo-pagina's voor hen niet altijd de prioriteit zijn. We zullen de opgemerkte fout noteren en ten gepaste tijde doorgeven aan hen. @coemans heeft zijn advies geformuleerd, aan jullie om te afweging te maken tussen zijn advies en het advies "**can be** confusing en should be avoided **where possible**"

**Comment by coemans** [comment]
@driesva uiteraard is het te vermijden en zelfs af te raden om de volgorde van de headings niet logisch te rangschikken of headings over te slaan puur voor visuele doeleinden. Op dezelfde website staat:

> Skipping heading ranks can be confusing and should be avoided where possible.

Dus te vermijden, maar het is geen probleem als je een grondige reden hebt om het wel te doen. Er zijn ontzettend veel screen readers en elke leverancier heeft een eigen implementatie. Mij werd verteld dat de meeste exemplaren hiermee overweg kunnen, maar het is natuurlijk veiliger om het niet te doen.
